# tasks file for NSClient++
---

- name: Create setup folder
  win_file:
    path: C:\sources
    state: directory

- name: Check for "NSClient++"
  win_stat:
    path: "c:\\sources\\NSCP-0.5.0.62-x64.msi"
  register: msipackagestat

- name: Download "NSClient++"
  win_get_url:
    url: "https://github.com/mickem/nscp/releases/download/0.5.2.41/NSCP-0.5.2.41-x64.msi"
    dest: "C:\\sources\\NSCP-0.5.2.41-x64.msi"
  when: not msipackagestat.stat.exists

- name: Install "NSClient++"
  win_package:
    path: "C:\\sources\\NSCP-0.5.2.41-x64.msi"
    state: present
  when: not msipackagestat.stat.exists

- name: Update NSClient++ configuration
  win_template:
    src: programfiles/nsclient/nsclient.ini.j2
    dest: "C:\\Program Files\\NSClient++\\nsclient.ini"
  notify: restart nsclient
  tags:
    - configuration

- name: Copy nsclient private key
  ansible.windows.win_copy:
    src: ../files/nsclient.key
    dest: C:\Program Files\NSClient++\security\nsclient.key
  when: nsclient_nrpe_usessl == 1

- name: Copy nsclient cert
  ansible.windows.win_copy:
    src: ../files/nsclient.pem
    dest: C:\Program Files\NSClient++\security\nsclient.pem
  when: nsclient_nrpe_usessl == 1

- name: Copy librenms CA cert
  ansible.windows.win_copy:
    src: ../files/ca_cert.pem
    dest: C:\Program Files\NSClient++\security\ca_cert.pem
  when: nsclient_nrpe_usessl == 1

- name: Restart NSClient++
  win_service:
    name: nscp
    state: restarted
